version: '3.8'

services:
  seamless:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    image: seamless-communication:latest
    container_name: seamless-communication
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    command: /bin/bash
